import PixelPilotCore
import SwiftUI

/// The warmth slider's track, and where things sit on it.
///
/// Extracted the moment a second surface wanted it. The schedule's stops set a
/// white point exactly as a display's colour card does, and a warmth slider
/// that ran through different colours in one place than the other would be two
/// controls pretending to be one — which is the failure `Components.swift`
/// opens by describing.
enum KelvinTrack {
  /// Where the slider sits when warmth is switched on. Not the neutral point:
  /// turning warmth on and seeing nothing happen reads as broken.
  static let defaultKelvin: Double = 4500

  static func fraction(of kelvin: Double) -> Double {
    let range = ColorTemperature.range
    return (kelvin - range.lowerBound) / (range.upperBound - range.lowerBound)
  }

  /// The neutral point is the one place on this track worth finding again, and
  /// the two ends are worth feeling. Quarters of a Kelvin range mean nothing.
  static let detents: [Double] = [0, fraction(of: ColorTemperature.neutralKelvin), 1]

  /// The track, generated by the same maths that drives the hardware.
  ///
  /// That is what makes it a preview rather than a decoration: every stop is a
  /// real white point from `ColorTemperature`, so the colour under the handle
  /// is the colour the screen is about to become. Computed once — a gradient of
  /// 29 stops costs nothing to keep around.
  static let gradient: LinearGradient = {
    let stops = stride(from: ColorTemperature.range.lowerBound,
                       through: ColorTemperature.range.upperBound,
                       by: 250).map { kelvin -> Gradient.Stop in
      let point = ColorTemperature.whitePoint(kelvin: kelvin)
      return Gradient.Stop(
        color: Color(red: point.red, green: point.green, blue: point.blue),
        location: fraction(of: kelvin)
      )
    }
    return LinearGradient(stops: stops, startPoint: .leading, endPoint: .trailing)
  }()

  /// Warm, Neutral, Cool under the track. The labels are half the reason the
  /// slider is readable at all — a bare gradient does not say which end is which
  /// to anyone who has not used one before.
  static var scaleLabels: some View {
    HStack {
      Text("Warm").font(TypeScale.detail).foregroundStyle(.secondary)
      Spacer()
      Text("Neutral").font(TypeScale.detail).foregroundStyle(.secondary)
      Spacer()
      Text("Cool").font(TypeScale.detail).foregroundStyle(.secondary)
    }
  }
}
